// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLd8fRKIElXdpx2tMn-SI5LRP_5vcICd4',
    appId: '1:156838446582:web:432888bdd71d87be47b3d7',
    messagingSenderId: '156838446582',
    projectId: 'flutter-starter-65c95',
    authDomain: 'flutter-starter-65c95.firebaseapp.com',
    storageBucket: 'flutter-starter-65c95.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKtR1SMzAEp_L6V5cDlsP6n0vCC10gWU',
    appId: '1:156838446582:android:3a8990e94face66147b3d7',
    messagingSenderId: '156838446582',
    projectId: 'flutter-starter-65c95',
    storageBucket: 'flutter-starter-65c95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtps6G-MTzqGEYSylYbwQjfYOx1Jq-nAw',
    appId: '1:156838446582:ios:e042504022e68c7b47b3d7',
    messagingSenderId: '156838446582',
    projectId: 'flutter-starter-65c95',
    storageBucket: 'flutter-starter-65c95.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtps6G-MTzqGEYSylYbwQjfYOx1Jq-nAw',
    appId: '1:156838446582:ios:1944b6cc4e1bb81147b3d7',
    messagingSenderId: '156838446582',
    projectId: 'flutter-starter-65c95',
    storageBucket: 'flutter-starter-65c95.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
